In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv(r"C:\Users\bhanu\Downloads\NIT\03 JUNE\14th\14th\EMP SAL.csv")

In [3]:
dataset

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [4]:
x= dataset.iloc[:,1:2].values
y= dataset.iloc[:,2].values

In [5]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [6]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000], dtype=int64)

# fitting svr to the dataset

In [7]:
from sklearn.svm import SVR
regressor = SVR()
regressor.fit(x,y)

SVR()

In [8]:
#predicting new result
y_pred_svr=regressor.predict([[6.5]])
y_pred_svr

array([130001.82883924])

# using for loop svr(support vector regression)

In [9]:
#create a range of degrees
degrees=[2,3,4,5,6,7]

In [16]:
#Fit and predict for each degree
for degree in degrees:
    regressor = SVR(kernel="linear",degree=degree)
    regressor.fit(x,y)
 #predicting a new result with polynomial regression for each degree with kernal="linear"
    prediction=y_pred_svr=regressor.predict([[6.5]])
    print(f"Predicted Salary (Degree{degrees}):{prediction[0]}")

Predicted Salary (Degree[2, 3, 4, 5, 6, 7]):130025.0
Predicted Salary (Degree[2, 3, 4, 5, 6, 7]):130025.0
Predicted Salary (Degree[2, 3, 4, 5, 6, 7]):130025.0
Predicted Salary (Degree[2, 3, 4, 5, 6, 7]):130025.0
Predicted Salary (Degree[2, 3, 4, 5, 6, 7]):130025.0
Predicted Salary (Degree[2, 3, 4, 5, 6, 7]):130025.0


In [15]:
for degree in degrees:
    regressor1 = SVR(kernel="poly",degree=degree)
    regressor1.fit(x,y)
#predicting a new result with polynomial regression for each degree with kernal="poly"
    Prediction1 = y_pred_svr=regressor1.predict([[6.5]])
    print(f"Predicted Salary (Degree {degree}):{Prediction1[0]}")

Predicted Salary (Degree 2):130047.47474816321
Predicted Salary (Degree 3):130477.49672141299
Predicted Salary (Degree 4):134160.63306166738
Predicted Salary (Degree 5):164079.01344549266
Predicted Salary (Degree 6):130259.7955733435
Predicted Salary (Degree 7):123664.81503285316


In [19]:
for degree in degrees:
    regressor2 =SVR(kernel="sigmoid",degree=degree)
    regressor2.fit(x,y)
#predicting a new result with polynomial regression for each degree with kernal="sigmoid"
    Prediction2 = y_pred_svr=regressor2.predict([[6.5]])
    print(f"Predicted Salary(Degree{degree}):{Prediction2[0]}")

Predicted Salary(Degree2):129999.84412875623
Predicted Salary(Degree3):129999.84412875623
Predicted Salary(Degree4):129999.84412875623
Predicted Salary(Degree5):129999.84412875623
Predicted Salary(Degree6):129999.84412875623
Predicted Salary(Degree7):129999.84412875623


# fitting KNN  to the ddataset

In [22]:
from sklearn.neighbors import KNeighborsRegressor
regressor_knn = KNeighborsRegressor(n_neighbors=6)
regressor_knn.fit(x,y)
#predicting a new result
y_pred_knn = regressor_knn.predict([[6.5]]) # by-default n_neighbors=5,algorithm="auto"
y_pred_knn

array([223333.33333333])

# using loop for KNN(K NEAREST NEIGHBOUR)

In [24]:
# create a range of degrees
neighbours=[2,3,4,5,6,7]

In [28]:
# Fit and predict for each number of neighbours
for n_neighbors in neighbours:
    regressor_knn=KNeighborsRegressor(n_neighbors)#by default algorithm="auto"
    regressor_knn.fit(x,y)
#predicting a new result with KNneighbours for each number of neighbors
    y_pred_knn = regressor_knn.predict([[6.5]])
    print(f"Predicted Salary (Number of Neighbors{n_neighbors}):{y_pred_knn[0]}")

Predicted Salary (Number of Neighbors2):175000.0
Predicted Salary (Number of Neighbors3):153333.33333333334
Predicted Salary (Number of Neighbors4):190000.0
Predicted Salary (Number of Neighbors5):168000.0
Predicted Salary (Number of Neighbors6):223333.33333333334
Predicted Salary (Number of Neighbors7):334285.71428571426


In [29]:
#different algo {'auto','ball_tree','kd_tree','brute'}

In [32]:
# Fit and predict for each number of neighbours
for n_neighbors in neighbours:
    regressor_knn=KNeighborsRegressor(n_neighbors,algorithm='ball_tree')# algorithm='ball_tree'
    regressor_knn.fit(x,y)
#predicting a new result with KNneighbours for each number of neighbors
    y_pred_knn = regressor_knn.predict([[6.5]])
    print(f"Predicted Salary (Number of Neighbors{n_neighbors}):{y_pred_knn[0]}")

Predicted Salary (Number of Neighbors2):175000.0
Predicted Salary (Number of Neighbors3):153333.33333333334
Predicted Salary (Number of Neighbors4):190000.0
Predicted Salary (Number of Neighbors5):168000.0
Predicted Salary (Number of Neighbors6):223333.33333333334
Predicted Salary (Number of Neighbors7):200000.0


In [35]:
# Fit and predict for each number of neighbours
for n_neighbors in neighbours:
    regressor_knn=KNeighborsRegressor(n_neighbors,algorithm='kd_tree')# algorithm='kd_tree'
    regressor_knn.fit(x,y)
#predicting a new result with KNneighbours for each number of neighbors
    y_pred_knn = regressor_knn.predict([[6.5]])
    print(f"Predicted Salary (Number of Neighbors{n_neighbors}):{y_pred_knn[0]}")

Predicted Salary (Number of Neighbors2):175000.0
Predicted Salary (Number of Neighbors3):153333.33333333334
Predicted Salary (Number of Neighbors4):190000.0
Predicted Salary (Number of Neighbors5):168000.0
Predicted Salary (Number of Neighbors6):223333.33333333334
Predicted Salary (Number of Neighbors7):200000.0


In [36]:
# Fit and predict for each number of neighbours
for n_neighbors in neighbours:
    regressor_knn=KNeighborsRegressor(n_neighbors,algorithm='brute')#by default algorithm="brute"
    regressor_knn.fit(x,y)
#predicting a new result with KNneighbours for each number of neighbors
    y_pred_knn = regressor_knn.predict([[6.5]])
    print(f"Predicted Salary (Number of Neighbors{n_neighbors}):{y_pred_knn[0]}")

Predicted Salary (Number of Neighbors2):175000.0
Predicted Salary (Number of Neighbors3):153333.33333333334
Predicted Salary (Number of Neighbors4):190000.0
Predicted Salary (Number of Neighbors5):168000.0
Predicted Salary (Number of Neighbors6):223333.33333333334
Predicted Salary (Number of Neighbors7):334285.71428571426


# DECISION TREE REGRESSION

In [37]:
# data into split (train,test)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [39]:
#feature scalilng
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
sc_y=StandardScaler()
y_train=sc_y.fit_transform(y_train.reshape(-2,2))

In [41]:
# fitting decision tree regression to the data set
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()#by-default criterion='squared_error',splitter='best'
regressor.fit(x,y)

DecisionTreeRegressor()

In [42]:
# predicting a new result
y_pred = regressor.predict([[6.5]])
y_pred

array([150000.])

In [ ]:
#different criterion('absolute_error','friedman_mse','poisson')

In [43]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()#by-default criterion='absolute_error',splitter='best'
regressor.fit(x,y)
y_pred = regressor.predict([[6.5]])
y_pred

array([150000.])

In [44]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()#by-default criterion='friedman_mse',splitter='best'
regressor.fit(x,y)
y_pred = regressor.predict([[6.5]])
y_pred

array([150000.])

In [45]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()#by-default criterion='poisson',splitter='best'
regressor.fit(x,y)
y_pred = regressor.predict([[6.5]])
y_pred

array([150000.])

# RANDOM FOREST REGRESSION

In [49]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=15)
regressor.fit(x,y)

RandomForestRegressor(n_estimators=15)

In [50]:
#predicting new result
y_pred= regressor.predict([[6.5]])
y_pred

array([168000.])

In [ ]:
# checking the predicted values after changing n_estimators


In [51]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100)
regressor.fit(x,y)
y_pred= regressor.predict([[6.5]])
y_pred

array([159100.])

In [52]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=75)
regressor.fit(x,y)
y_pred= regressor.predict([[6.5]])
y_pred

array([169066.66666667])

In [53]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=50)
regressor.fit(x,y)
y_pred= regressor.predict([[6.5]])
y_pred

array([160600.])

In [54]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=25)
regressor.fit(x,y)
y_pred= regressor.predict([[6.5]])
y_pred

array([164800.])

In [55]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=250)
regressor.fit(x,y)
y_pred= regressor.predict([[6.5]])
y_pred

array([167520.])